#!/usr/bin/env bash
# Testing-cockpit mode: unique MCP name + fixture injector exist (no live glass).
set -euo pipefail
ROOT="${1:?}"
test -f "$ROOT/scripts/dogfood-up.sh"
test -f "$ROOT/scripts/dogfood-down.sh"
test -f "$ROOT/scripts/dogfood-e2e.sh"
test -f "$ROOT/scripts/lib/dogfood-paths.sh"
test -f "$ROOT/scripts/cursor-dogfood-mcp.sh"
test -f "$ROOT/scripts/cursor-kernel-mcp.sh"
test -f "$ROOT/scripts/cockpit-mcp-preflight.sh"
test -f "$ROOT/.cursor/mcp.json"
test -f "$ROOT/.cursor/rules/cockpit-e2e.mdc"
test -f "$ROOT/docs/CURSOR-E2E.md"
test -f "$ROOT/.grok/commands/cockpit-dogfood-e2e.md"
grep -q '.cockpit-dogfood' "$ROOT/.gitignore"
grep -q 'cockpit-research-dogfood' "$ROOT/.cursor/mcp.json"
grep -q 'dogfood_default_dest' "$ROOT/scripts/dogfood-up.sh"
grep -q 'dogfood_resolve_vault' "$ROOT/scripts/lib/dogfood-paths.sh"
grep -q '/home/ubuntu/cockpit-vault' "$ROOT/scripts/lib/dogfood-paths.sh"
grep -q '/home/ubuntu/cockpit-vault' "$ROOT/docs/CURSOR-E2E.md"
grep -q 'cockpit/lib/fm.js' "$ROOT/scripts/dogfood-up.sh"
grep -q 'cursor-dogfood-mcp.sh' "$ROOT/.cursor/mcp.json"
grep -q 'cursor-kernel-mcp.sh' "$ROOT/.cursor/mcp.json"
grep -q 'COCKPIT_ENV_QUIET=1' "$ROOT/scripts/cursor-kernel-mcp.sh"
grep -q 'cockpit-mcp-preflight.sh' "$ROOT/docs/CURSOR-E2E.md"
test -f "$ROOT/memory-cockpit-v2/scripts/dogfood-fixture.mjs"
test -f "$ROOT/memory-cockpit-v2/scripts/dogfood-seed-desks.mjs"
test -f "$ROOT/memory-cockpit-v2/scripts/dogfood-seed-desks-test.mjs"
test -f "$ROOT/memory-cockpit-v2/scripts/write-dogfood-pin.mjs"
test -f "$ROOT/memory-cockpit-v2/scripts/mcp-name-isolation-test.mjs"
grep -q 'mcpServerName' "$ROOT/memory-cockpit-v2/server/cockpitMcpProject.js"
grep -q 'cockpit-research-dogfood' "$ROOT/scripts/dogfood-up.sh"
grep -q 'pwd -P' "$ROOT/scripts/dogfood-up.sh"
grep -q 'cockpit-vault' "$ROOT/scripts/dogfood-up.sh"
grep -q 'is_live_tree' "$ROOT/scripts/dogfood-up.sh"
grep -q 'is_live_tree' "$ROOT/scripts/dogfood-down.sh"
grep -q 'must not pin mcp_servers.cockpit-research' "$ROOT/memory-cockpit-v2/server/cockpitMcpProject.js"
grep -q 'assertInjectableRoot' "$ROOT/memory-cockpit-v2/scripts/dogfood-fixture.mjs"
grep -q 'fixtureLane' "$ROOT/memory-cockpit-v2/server/secEdgar.js"
grep -q 'BASH_VERSION' "$ROOT/scripts/dogfood-up.sh"
(cd "$ROOT/memory-cockpit-v2" && node scripts/mcp-name-isolation-test.mjs)
(cd "$ROOT/memory-cockpit-v2" && node scripts/dogfood-fixture-test.mjs)
(cd "$ROOT/memory-cockpit-v2" && node scripts/dogfood-seed-desks-test.mjs)
echo "    dogfood-mode OK"
